#!/bin/bash

# Pulser Updater

usage() {
	cat <<EOM
Usage:

$(basename $0)
    Module Name
    Text
    Value (0 - 100)
    State (created/progress/ongoing/finished)
    Urgency (low/med/high)

eg. '$(basename $0) "Test Application" "Description" 100 progress low'
EOM
	exit 1
}

if [[ $# -lt 2 ]]; then
	usage
fi

url="localhost:8080" # Edit to point to the pulser server

# Replace any spaces in module name to html escape them
application_slug=$1
application_slug="${application_slug// /\%20}"

text=$2
value=$3
state=$4
urgency=$5

res=$(curl -s -X POST -d text="$text" -d value="$value" -d state="$state" -d urgency="$urgency" http://$url/api/applications/$application_slug/updates | cat)

echo $res
regex="\"status\":\"(error|success)\""

if [[ $res =~ $regex ]]; then
	echo ${BASH_REMATCH[1]}
	if [[ ${BASH_REMATCH[1]} == "success" ]]; then
		exit 0
	else
		exit 1
	fi
fi
